#Connection mit MySQL nötig wenn die Perks nicht beim rejoinen verschwinden sollen.
#MYSQL CONNECT
MySQL:
  username:
  password:
  database:
  port:
  host:

#Prefix des Plugins (Nicht als eigenes Ausgeben).
PluginPrefix:
  Prefix: "§c§LMoLunar§8» "

#Permissions von den Befehlen.
Permissions:
  Heal: "molunar.heal"
  Feed: "molunar.feed"
  Kick: "molunar.kick"
  Wartung: "molunar.wartung"
  Gamemode: "molunar.gamemode"
  Broadcast: "molunar.broadcast"
  ChatClear: "molunar.chatclear"
  Fly: "molunar.fly"
  Mentation: "molunar.mentation"


